apiVersion: v1
kind: Service
metadata:
  name: {{ include "policy-server.fullname" . }}-prometheus
  labels:
    {{- include "policy-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port2 }}
      targetPort: {{ .Values.service.port2 }}
      protocol: TCP
      name: http
  selector:
    {{- include "policy-server.selectorLabels" . | nindent 4 }}
