version: "3.9"
services:
  ray_serve:
    build: .
    ports:
      - "8000:8000" # FastAPI endpoints
      - "8080:8080" # Metrics collection
      - "8256:8256" # Ray dashboard
    environment:
      USE_RAY: "True"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    image: "prom/prometheus"

  grafana:
    ports:
      - "3000:3000"
    image: "grafana/grafana:latest"
    links:
      - "prometheus"

  fluentd:
    image: "fluent/fluentd"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: "elasticsearch:6.5.0"
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: "kibana:7.10.1"
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
