swagger: "2.0"
info:
  description: "This is a simple showcase of generating a policy server API for Pathmind's\
    \ Lagor Proof of Concept."
  version: "0.1"
  title: "Pathmind LPoC policy prediction service"
  contact:
    email: "info@pathmind.com"

basePath: "/api"
tags:
  - name: "Prediction"
    description: "Access policy to predict actions from states"
  - name: "Authentication"
    description: "Log in and out of our service"
  - name: "Models"
    description: "Endpoints to update the policy"
  - name: "Docs"
    description: "Documentation endpoints"
  - name: "Clients"
    description: "Download SDKs in several languages."
schemes:
  - "https"
  - "http"

paths:
  /model:
    post:
      summary: "Post a TensorFlow SavedModel (.zip), PyTorch (.pt, .pth)."
      operationId: "api.save_model"
      tags:
        - "Models"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "model_file"
          type: "file"
          description: "The model file to upload."
      responses:
        "200":
          description: "Posted valid model"
        "405":
          description: "Invalid input"
      security:
        - basicAuth: []
  /preprocessor:
    post:
      summary: "Post a preprocessor Python script. Needs to have a function called 'preprocess' in that file."
      operationId: "api.save_preprocessor"
      tags:
        - "Models"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "preprocessor_file"
          type: "file"
          description: "The preprocessor file to upload."
      responses:
        "200":
          description: "Posted valid preprocessor"
        "405":
          description: "Invalid input"
      security:
        - basicAuth: []
  /outputmapper:
    post:
      summary: "JSON file mapping actions to meanings."
      operationId: "api.save_output_mapper"
      tags:
        - "Models"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: "formData"
          name: "output_mapper_file"
          type: "file"
          description: "Output mapper YAML file."
      responses:
        "200":
          description: "Posted valid output mapper"
        "405":
          description: "Invalid input"
      security:
        - basicAuth: []
  /predict:
    post:
      tags:
      - "Prediction"
      summary: "Predict a new action for the current state"
      operationId: "api.predict"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "observation"
        description: "Observation to be fed into the policy to receive the next action"
        required: true
        schema:
          $ref: "#/definitions/Observation"
      responses:
        "200":
          description: "Successfully computed next action"
          schema:
            $ref: "#/definitions/Prediction"
        "405":
          description: "Invalid input"
      security:
        - basicAuth: []
  /clients:
    get:
      tags:
        - "Clients"
      operationId: "api.clients"
      summary: "Returns zip file with Python and Java client SDKs for this server."
      produces:
        - "application/zip"
      responses:
        200:
          description: A zip file with clients.
          schema:
            type: file
      security:
        - basicAuth: []

securityDefinitions:
  basicAuth:
    type: "basic"
    x-basicInfoFunc: api.basic_auth

definitions: 
  Prediction:
    type: "object"
    properties:
      action:
        type: "integer"
        format: "int32"
      meaning:
        type: "string"
    example:
      meaning: "meaning"
      action: 0
 
  Observation:
    type: "object"
    required:
      - id
      - name
      - coordinates
      - has_left_neighbour
      - has_up_neighbour
      - has_right_neighbour
      - has_down_neighbour
      - has_core
      - target
    properties:
      id:
        type: "integer"
        format: "int32"
        example: 0
        description: "Table ID"
      name:
        type: "string"
        example: "pt07_c"
        description: "Name of the node the table is on."
      has_left_neighbour:
        type: "boolean"
        description: "Is there a node available to the left?"
        example: True
      is_left_free:
        type: "boolean"
        description: "Is the leftward node free?"
        example: False
      has_up_neighbour:
        type: "boolean"
      is_up_free:
        type: "boolean"
      has_right_neighbour:
        type: "boolean"
      is_right_free:
        type: "boolean"
      has_down_neighbour:
        type: "boolean"
      is_down_free:
        type: "boolean"
      coordinates:
        type: "array"
        example:
        - 1
        - 1
        items:
          type: "integer"
        maxItems: 2
        minItems: 2
      has_core:
        type: "boolean"
      target:
        type: "array"
        example:
        - 6
        - 2
        items:
          type: "integer"
        maxItems: 2
        minItems: 2