info:
  description: "Mouse and Cheese example"
  version: "0.1"
  title: "Pathmind Mouse and Cheese policy prediction service"
  contact:
    email: "info@pathmind.com"

Observation:
  type: "object"
  required:
    - mouse_row
    - mouse_col
  properties:
    mouse_row:
      type: "number"
      format: "float"
      example: 1
      description: "Vertical mouse position ('row') between 0 and 5"
    mouse_col:
      type: "number"
      format: "float"
      example: 2
      description: "Horizontal mouse position ('col') between 0 and 5"