# int, float, bool, str, List[int], List[float]
observations:
  mouse_row:
    type: float
  mouse_col:
    type: float
  mouse_row_distance:
    type: float
  mouse_col_distance:
    type: float
  cheese_row:
    type: float
  cheese_col:
    type: float

parameters:
  discrete: True
  tuple: False
  api_key: "1234567asdfgh"
