observations:
  id:
    type: int
  coordinates_0:
    type: int
  coordinates_1:
    type: int
  has_up_neighbour:
    type: bool
  is_up_free:
    type: bool
  has_right_neighbour:
    type: bool
  is_right_free:
    type: bool
  has_down_neighbour:
    type: bool
  is_down_free:
    type: bool
  has_left_neighbour:
    type: bool
  is_left_free:
    type: bool

parameters:
  discrete: True
  tuple: False
  api_key: "1234567asdfgh"
