def preprocess(obs):
    return [
        obs.get("manufacturing_center_0_stock") / 1000,
        obs.get("manufacturing_center_1_stock") / 1000,
        obs.get("manufacturing_center_2_stock") / 1000,
        obs.get("manufacturing_center_0_total_vehicles") / 3,
        obs.get("manufacturing_center_1_total_vehicles") / 3,
        obs.get("manufacturing_center_2_total_vehicles") / 3,
        obs.get("manufacturing_center_0_idle_vehicles") / 3,
        obs.get("manufacturing_center_1_idle_vehicles") / 3,
        obs.get("manufacturing_center_2_idle_vehicles") / 3,
        obs.get("distributor_0_order_amount") / 1000,
        obs.get("distributor_1_order_amount") / 1000,
        obs.get("distributor_2_order_amount") / 1000,
        obs.get("distributor_3_order_amount") / 1000,
        obs.get("distributor_4_order_amount") / 1000,
        obs.get("distributor_5_order_amount") / 1000,
        obs.get("distributor_6_order_amount") / 1000,
        obs.get("distributor_7_order_amount") / 1000,
        obs.get("distributor_8_order_amount") / 1000,
        obs.get("distributor_9_order_amount") / 1000,
        obs.get("distributor_10_order_amount") / 1000,
        obs.get("distributor_11_order_amount") / 1000,
        obs.get("distributor_12_order_amount") / 1000,
        obs.get("distributor_13_order_amount") / 1000,
        obs.get("distributor_14_order_amount") / 1000,
    ]
