Observation:
  type: "object"
  required:
    - hour
    - day
    - month
    - 30_minute_cost
    - price
    - total_cost
  properties:
    hour:
      type: "number"
      format: "int"
      example: 8
      minimum: 1
      maximum: 24
      description: "Time of day"
    day:
      type: "number"
      format: "int"
      example: 127
      minimum: 1
      maximum: 365
      description: "Day of year"
    month:
      type: "number"
      format: "int"
      example: 5
      minimum: 1
      maximum: 12
      description: "Month of year"
    30_minute_cost:
      type: "number"
      format: "float"
      example: 123.45
      minimum: 0
      maximum: 10000
      description: "Rolling 30 minute cost"
    price:
      type: "number"
      format: "float"
      example: 123.45
      minimum: -100
      maximum: 500
      description: "Electricity prices"
    total_cost:
      type: "number"
      format: "float"
      example: 123.45
      minimum: 0
      maximum: 2000000
      description: "Total Cost"
