observations:
  total_products_processed:
    type: float
  machine1_seized:
    type: float
  machine2_seized:
    type: float
  seizeDelayStage1_queue:
    type: float
  seizeDelayStage2_queue:
    type: float
  seizeDelayStage3_queue:
    type: float

parameters:
  discrete: True
  tuple: True
  api_key: "1234567asdfgh"
